### ISSUE TITLE
JSIL fails to build on Mono 3.2.6 / Mac

### ISSUE THREAD

**Issue by thefiddler** [Protobuild/Protobuild#22]
Reproduced as follows:

```
git clone https://github.com/mono/MonoGame
cd MonoGame
git submodule init
git submodule update
mono Protobuild.exe
```

The same steps on Windows appear to work correctly. My mono version is:

```
mono --version
Mono JIT compiler version 3.2.6 ((no/9b58377 Thu Jan 16 17:49:56 EST 2014)
Copyright (C) 2002-2012 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
    TLS:           normal
    SIGSEGV:       altstack
    Notification:  kqueue
    Architecture:  x86
    Disabled:      none
    Misc:          softdebug 
    LLVM:          yes(3.3svn-mono-(no/8bdedb5)
    GC:            sgen
```

The build output:

```

/Users/[snip]/.config/.jsil/source/Compiler/Compiler.csproj (default targets) ->
/Library/Frameworks/Mono.framework/Versions/3.2.6/lib/mono/4.0/Microsoft.Common.targets (ResolveProjectReferences target) ->
/Users/[snip]/.config/.jsil/source/JSIL/JSIL.csproj (default targets) ->
/Library/Frameworks/Mono.framework/Versions/3.2.6/lib/mono/4.0/Microsoft.Common.targets (ResolveProjectReferences target) ->
/Users/[snip]/.config/.jsil/source/Upstream/ILSpy/ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj (default targets) ->
/Library/Frameworks/Mono.framework/Versions/3.2.6/lib/mono/4.0/Microsoft.CSharp.Targets (CoreCompile target) ->

    Ast/NRefactoryExtensions.cs(27,19): error CS1110: `ICSharpCode.Decompiler.Ast.NRefactoryExtensions.WithAnnotation<T>(this T, object)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    Ast/NRefactoryExtensions.cs(34,19): error CS1110: `ICSharpCode.Decompiler.Ast.NRefactoryExtensions.CopyAnnotationsFrom<T>(this T, ICSharpCode.NRefactory.CSharp.AstNode)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    Ast/NRefactoryExtensions.cs(42,19): error CS1110: `ICSharpCode.Decompiler.Ast.NRefactoryExtensions.Detach<T>(this T)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    Ast/NRefactoryExtensions.cs(48,28): error CS1110: `ICSharpCode.Decompiler.Ast.NRefactoryExtensions.WithName(this ICSharpCode.NRefactory.CSharp.Expression, string)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    Ast/NRefactoryExtensions.cs(53,27): error CS1110: `ICSharpCode.Decompiler.Ast.NRefactoryExtensions.WithName(this ICSharpCode.NRefactory.CSharp.Statement, string)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    Ast/NRefactoryExtensions.cs(58,22): error CS1110: `ICSharpCode.Decompiler.Ast.NRefactoryExtensions.AddNamedArgument(this ICSharpCode.NRefactory.CSharp.Attribute, string, ICSharpCode.NRefactory.CSharp.Expression)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    Ast/NRefactoryExtensions.cs(63,25): error CS1110: `ICSharpCode.Decompiler.Ast.NRefactoryExtensions.ToType(this ICSharpCode.NRefactory.PatternMatching.Pattern)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    Ast/NRefactoryExtensions.cs(68,28): error CS1110: `ICSharpCode.Decompiler.Ast.NRefactoryExtensions.ToExpression(this ICSharpCode.NRefactory.PatternMatching.Pattern)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    Ast/NRefactoryExtensions.cs(73,27): error CS1110: `ICSharpCode.Decompiler.Ast.NRefactoryExtensions.ToStatement(this ICSharpCode.NRefactory.PatternMatching.Pattern)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    Ast/NRefactoryExtensions.cs(78,27): error CS1110: `ICSharpCode.Decompiler.Ast.NRefactoryExtensions.GetNextStatement(this ICSharpCode.NRefactory.CSharp.Statement)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    CecilExtensions.cs(33,21): error CS1110: `ICSharpCode.Decompiler.CecilExtensions.GetPushDelta(this Mono.Cecil.Cil.Instruction)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    CecilExtensions.cs(62,22): error CS1110: `ICSharpCode.Decompiler.CecilExtensions.GetPopDelta(this Mono.Cecil.Cil.Instruction, Mono.Cecil.MethodDefinition)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    CecilExtensions.cs(114,22): error CS1110: `ICSharpCode.Decompiler.CecilExtensions.IsVoid(this Mono.Cecil.TypeReference)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    CecilExtensions.cs(121,22): error CS1110: `ICSharpCode.Decompiler.CecilExtensions.IsValueTypeOrVoid(this Mono.Cecil.TypeReference)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    CecilExtensions.cs(134,21): error CS1110: `ICSharpCode.Decompiler.CecilExtensions.GetEndOffset(this Mono.Cecil.Cil.Instruction)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    CecilExtensions.cs(146,43): error CS1110: `ICSharpCode.Decompiler.CecilExtensions.GetAccessorMethods(this Mono.Cecil.TypeDefinition)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    CecilExtensions.cs(169,32): error CS1110: `ICSharpCode.Decompiler.CecilExtensions.ResolveWithinSameModule(this Mono.Cecil.TypeReference)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    CecilExtensions.cs(177,33): error CS1110: `ICSharpCode.Decompiler.CecilExtensions.ResolveWithinSameModule(this Mono.Cecil.FieldReference)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    CecilExtensions.cs(185,34): error CS1110: `ICSharpCode.Decompiler.CecilExtensions.ResolveWithinSameModule(this Mono.Cecil.MethodReference)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    CecilExtensions.cs(193,32): error CS1110: `ICSharpCode.Decompiler.CecilExtensions.ResolveOrThrow(this Mono.Cecil.TypeReference)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    CecilExtensions.cs(201,22): error CS1110: `ICSharpCode.Decompiler.CecilExtensions.IsCompilerGenerated(this Mono.Cecil.ICustomAttributeProvider)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    CecilExtensions.cs(212,22): error CS1110: `ICSharpCode.Decompiler.CecilExtensions.IsCompilerGeneratedOrIsInCompilerGeneratedClass(this Mono.Cecil.IMemberDefinition)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    CecilExtensions.cs(221,31): error CS1110: `ICSharpCode.Decompiler.CecilExtensions.GetEnumUnderlyingType(this Mono.Cecil.TypeDefinition)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    CecilExtensions.cs(238,22): error CS1110: `ICSharpCode.Decompiler.CecilExtensions.IsAnonymousType(this Mono.Cecil.TypeReference)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    CecilExtensions.cs(249,22): error CS1110: `ICSharpCode.Decompiler.CecilExtensions.HasGeneratedName(this Mono.Cecil.MemberReference)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    CecilExtensions.cs(254,22): error CS1110: `ICSharpCode.Decompiler.CecilExtensions.ContainsAnonymousType(this Mono.Cecil.TypeReference)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    CecilExtensions.cs(273,24): error CS1110: `ICSharpCode.Decompiler.CecilExtensions.GetDefaultMemberName(this Mono.Cecil.TypeDefinition)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    CecilExtensions.cs(279,24): error CS1110: `ICSharpCode.Decompiler.CecilExtensions.GetDefaultMemberName(this Mono.Cecil.TypeDefinition, out Mono.Cecil.CustomAttribute)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    CecilExtensions.cs(292,22): error CS1110: `ICSharpCode.Decompiler.CecilExtensions.IsIndexer(this Mono.Cecil.PropertyDefinition)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    CecilExtensions.cs(298,22): error CS1110: `ICSharpCode.Decompiler.CecilExtensions.IsIndexer(this Mono.Cecil.PropertyDefinition, out Mono.Cecil.CustomAttribute)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    CodeMappings.cs(166,35): error CS1110: `ICSharpCode.Decompiler.CodeMappings.GetInstructionByLineNumber(this ICSharpCode.Decompiler.MemberMapping, int, out int)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    CodeMappings.cs(192,35): error CS1110: `ICSharpCode.Decompiler.CodeMappings.GetInstructionByTokenAndOffset(this ICSharpCode.Decompiler.MemberMapping, int, out bool)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    CodeMappings.cs(228,22): error CS1110: `ICSharpCode.Decompiler.CodeMappings.GetInstructionByTokenAndOffset(this ICSharpCode.Decompiler.MemberMapping, int, out Mono.Cecil.MemberReference, out int)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    Disassembler/DisassemblerHelpers.cs(53,22): error CS1110: `ICSharpCode.Decompiler.Disassembler.DisassemblerHelpers.WriteTo(this Mono.Cecil.Cil.ExceptionHandler, ICSharpCode.Decompiler.ITextOutput)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    Disassembler/DisassemblerHelpers.cs(76,22): error CS1110: `ICSharpCode.Decompiler.Disassembler.DisassemblerHelpers.WriteTo(this Mono.Cecil.Cil.Instruction, ICSharpCode.Decompiler.ITextOutput)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    Disassembler/DisassemblerHelpers.cs(111,22): error CS1110: `ICSharpCode.Decompiler.Disassembler.DisassemblerHelpers.WriteTo(this Mono.Cecil.MethodReference, ICSharpCode.Decompiler.ITextOutput)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    Disassembler/DisassemblerHelpers.cs(150,15): error CS1110: `ICSharpCode.Decompiler.Disassembler.DisassemblerHelpers.WriteTo(this Mono.Cecil.FieldReference, ICSharpCode.Decompiler.ITextOutput)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    Disassembler/DisassemblerHelpers.cs(229,22): error CS1110: `ICSharpCode.Decompiler.Disassembler.DisassemblerHelpers.WriteTo(this Mono.Cecil.TypeReference, ICSharpCode.Decompiler.ITextOutput, ICSharpCode.Decompiler.Disassembler.ILNameSyntax)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/ILAstBuilder.cs(795,25): error CS1110: `ICSharpCode.Decompiler.ILAst.ILAstBuilderExtensionMethods.CutRange<T>(this System.Collections.Generic.List<T>, int, int)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/ILAstBuilder.cs(805,21): error CS1110: `ICSharpCode.Decompiler.ILAst.ILAstBuilderExtensionMethods.Union<T>(this T[], T)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/ILAstBuilder.cs(817,21): error CS1110: `ICSharpCode.Decompiler.ILAst.ILAstBuilderExtensionMethods.Union<T>(this T[], T[])': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/ILAstOptimizer.cs(707,22): error CS1110: `ICSharpCode.Decompiler.ILAst.ILAstOptimizerExtensionMethods.RunOptimization(this ICSharpCode.Decompiler.ILAst.ILBlock, System.Func<System.Collections.Generic.List<ICSharpCode.Decompiler.ILAst.ILNode>,ICSharpCode.Decompiler.ILAst.ILBasicBlock,int,bool>)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/ILAstOptimizer.cs(719,22): error CS1110: `ICSharpCode.Decompiler.ILAst.ILAstOptimizerExtensionMethods.RunOptimization(this ICSharpCode.Decompiler.ILAst.ILBlock, System.Func<System.Collections.Generic.List<ICSharpCode.Decompiler.ILAst.ILNode>,ICSharpCode.Decompiler.ILAst.ILExpression,int,bool>)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/ILAstOptimizer.cs(733,22): error CS1110: `ICSharpCode.Decompiler.ILAst.ILAstOptimizerExtensionMethods.IsConditionalControlFlow(this ICSharpCode.Decompiler.ILAst.ILNode)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/ILAstOptimizer.cs(739,22): error CS1110: `ICSharpCode.Decompiler.ILAst.ILAstOptimizerExtensionMethods.IsUnconditionalControlFlow(this ICSharpCode.Decompiler.ILAst.ILNode)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/ILAstOptimizer.cs(749,22): error CS1110: `ICSharpCode.Decompiler.ILAst.ILAstOptimizerExtensionMethods.HasNoSideEffects(this ICSharpCode.Decompiler.ILAst.ILExpression)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/ILAstOptimizer.cs(769,22): error CS1110: `ICSharpCode.Decompiler.ILAst.ILAstOptimizerExtensionMethods.IsStoreToArray(this ICSharpCode.Decompiler.ILAst.ILCode)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/ILAstOptimizer.cs(787,22): error CS1110: `ICSharpCode.Decompiler.ILAst.ILAstOptimizerExtensionMethods.IsLoadFromArray(this ICSharpCode.Decompiler.ILAst.ILCode)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/ILAstOptimizer.cs(811,22): error CS1110: `ICSharpCode.Decompiler.ILAst.ILAstOptimizerExtensionMethods.CanBeExpressionStatement(this ICSharpCode.Decompiler.ILAst.ILExpression)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/ILAstOptimizer.cs(843,30): error CS1110: `ICSharpCode.Decompiler.ILAst.ILAstOptimizerExtensionMethods.WithILRanges(this ICSharpCode.Decompiler.ILAst.ILExpression, System.Collections.Generic.IEnumerable<ICSharpCode.Decompiler.ILAst.ILRange>)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/ILAstOptimizer.cs(849,22): error CS1110: `ICSharpCode.Decompiler.ILAst.ILAstOptimizerExtensionMethods.RemoveTail(this System.Collections.Generic.List<ICSharpCode.Decompiler.ILAst.ILNode>, params ICSharpCode.Decompiler.ILAst.ILCode[])': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/ILAstOptimizer.cs(858,19): error CS1110: `ICSharpCode.Decompiler.ILAst.ILAstOptimizerExtensionMethods.GetOrDefault<K,V>(this System.Collections.Generic.Dictionary<K,V>, K)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/ILAstOptimizer.cs(865,22): error CS1110: `ICSharpCode.Decompiler.ILAst.ILAstOptimizerExtensionMethods.RemoveOrThrow<T>(this System.Collections.Generic.ICollection<T>, T)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/ILAstOptimizer.cs(871,22): error CS1110: `ICSharpCode.Decompiler.ILAst.ILAstOptimizerExtensionMethods.RemoveOrThrow<K,V>(this System.Collections.Generic.Dictionary<K,V>, K)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/ILAstOptimizer.cs(877,22): error CS1110: `ICSharpCode.Decompiler.ILAst.ILAstOptimizerExtensionMethods.ContainsReferenceTo(this ICSharpCode.Decompiler.ILAst.ILExpression, ICSharpCode.Decompiler.ILAst.ILVariable)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/ILCodes.cs(361,24): error CS1110: `ICSharpCode.Decompiler.ILAst.ILCodeUtil.GetName(this ICSharpCode.Decompiler.ILAst.ILCode)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/ILCodes.cs(366,22): error CS1110: `ICSharpCode.Decompiler.ILAst.ILCodeUtil.IsConditionalControlFlow(this ICSharpCode.Decompiler.ILAst.ILCode)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/ILCodes.cs(400,22): error CS1110: `ICSharpCode.Decompiler.ILAst.ILCodeUtil.IsUnconditionalControlFlow(this ICSharpCode.Decompiler.ILAst.ILCode)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/ILCodes.cs(487,37): error CS1110: `ICSharpCode.Decompiler.ILAst.ILCodeUtil.GetParameter(this Mono.Cecil.Cil.MethodBody, int)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/PatternMatching.cs(29,22): error CS1110: `ICSharpCode.Decompiler.ILAst.PatternMatching.Match(this ICSharpCode.Decompiler.ILAst.ILNode, ICSharpCode.Decompiler.ILAst.ILCode)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/PatternMatching.cs(35,22): error CS1110: `ICSharpCode.Decompiler.ILAst.PatternMatching.Match<T>(this ICSharpCode.Decompiler.ILAst.ILNode, ICSharpCode.Decompiler.ILAst.ILCode, out T)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/PatternMatching.cs(46,22): error CS1110: `ICSharpCode.Decompiler.ILAst.PatternMatching.Match(this ICSharpCode.Decompiler.ILAst.ILNode, ICSharpCode.Decompiler.ILAst.ILCode, out System.Collections.Generic.List<ICSharpCode.Decompiler.ILAst.ILExpression>)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/PatternMatching.cs(58,22): error CS1110: `ICSharpCode.Decompiler.ILAst.PatternMatching.Match(this ICSharpCode.Decompiler.ILAst.ILNode, ICSharpCode.Decompiler.ILAst.ILCode, out ICSharpCode.Decompiler.ILAst.ILExpression)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/PatternMatching.cs(69,22): error CS1110: `ICSharpCode.Decompiler.ILAst.PatternMatching.Match<T>(this ICSharpCode.Decompiler.ILAst.ILNode, ICSharpCode.Decompiler.ILAst.ILCode, out T, out System.Collections.Generic.List<ICSharpCode.Decompiler.ILAst.ILExpression>)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/PatternMatching.cs(82,22): error CS1110: `ICSharpCode.Decompiler.ILAst.PatternMatching.Match<T>(this ICSharpCode.Decompiler.ILAst.ILNode, ICSharpCode.Decompiler.ILAst.ILCode, out T, out ICSharpCode.Decompiler.ILAst.ILExpression)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/PatternMatching.cs(93,22): error CS1110: `ICSharpCode.Decompiler.ILAst.PatternMatching.Match<T>(this ICSharpCode.Decompiler.ILAst.ILNode, ICSharpCode.Decompiler.ILAst.ILCode, out T, out ICSharpCode.Decompiler.ILAst.ILExpression, out ICSharpCode.Decompiler.ILAst.ILExpression)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/PatternMatching.cs(106,22): error CS1110: `ICSharpCode.Decompiler.ILAst.PatternMatching.MatchSingle<T>(this ICSharpCode.Decompiler.ILAst.ILBasicBlock, ICSharpCode.Decompiler.ILAst.ILCode, out T, out ICSharpCode.Decompiler.ILAst.ILExpression)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/PatternMatching.cs(119,22): error CS1110: `ICSharpCode.Decompiler.ILAst.PatternMatching.MatchSingleAndBr<T>(this ICSharpCode.Decompiler.ILAst.ILBasicBlock, ICSharpCode.Decompiler.ILAst.ILCode, out T, out ICSharpCode.Decompiler.ILAst.ILExpression, out ICSharpCode.Decompiler.ILAst.ILLabel)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/PatternMatching.cs(134,22): error CS1110: `ICSharpCode.Decompiler.ILAst.PatternMatching.MatchLastAndBr<T>(this ICSharpCode.Decompiler.ILAst.ILBasicBlock, ICSharpCode.Decompiler.ILAst.ILCode, out T, out ICSharpCode.Decompiler.ILAst.ILExpression, out ICSharpCode.Decompiler.ILAst.ILLabel)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/PatternMatching.cs(147,22): error CS1110: `ICSharpCode.Decompiler.ILAst.PatternMatching.MatchThis(this ICSharpCode.Decompiler.ILAst.ILNode)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/PatternMatching.cs(153,22): error CS1110: `ICSharpCode.Decompiler.ILAst.PatternMatching.MatchLdloc(this ICSharpCode.Decompiler.ILAst.ILNode, ICSharpCode.Decompiler.ILAst.ILVariable)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/PatternMatching.cs(159,22): error CS1110: `ICSharpCode.Decompiler.ILAst.PatternMatching.MatchLdloca(this ICSharpCode.Decompiler.ILAst.ILNode, ICSharpCode.Decompiler.ILAst.ILVariable)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ILAst/PatternMatching.cs(165,22): error CS1110: `ICSharpCode.Decompiler.ILAst.PatternMatching.MatchStloc(this ICSharpCode.Decompiler.ILAst.ILNode, ICSharpCode.Decompiler.ILAst.ILVariable, out ICSharpCode.Decompiler.ILAst.ILExpression)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ITextOutput.cs(46,22): error CS1110: `ICSharpCode.Decompiler.TextOutputExtensions.Write(this ICSharpCode.Decompiler.ITextOutput, string, params object[])': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ITextOutput.cs(51,22): error CS1110: `ICSharpCode.Decompiler.TextOutputExtensions.WriteLine(this ICSharpCode.Decompiler.ITextOutput, string)': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?
    ITextOutput.cs(57,22): error CS1110: `ICSharpCode.Decompiler.TextOutputExtensions.WriteLine(this ICSharpCode.Decompiler.ITextOutput, string, params object[])': Extension methods require `System.Runtime.CompilerServices.ExtensionAttribute' type to be available. Are you missing an assembly reference?

     25 Warning(s)
     76 Error(s)

Time Elapsed 00:00:11.1719710
error!
Unable to build the JSIL compiler.  This may be caused by an 
incompatible change made in the upstream codebase.  Things you 
can try:

 1) Make sure you have the latest version of Protobuild
 2) If the problem still persists, file an issue at
    https://github.com/hach-que/Protobuild/issues
    with a copy of the above output.

=============================================================
```
